-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION` (
    `JOB_EXECUTION_ID` BIGINT NOT NULL,
    `VERSION` BIGINT NULL,
    `JOB_INSTANCE_ID` BIGINT NOT NULL,
    `CREATE_TIME` DATETIME(6) NOT NULL,
    `START_TIME` DATETIME(6) NULL,
    `END_TIME` DATETIME(6) NULL,
    `STATUS` VARCHAR(10) NULL,
    `EXIT_CODE` VARCHAR(2500) NULL,
    `EXIT_MESSAGE` VARCHAR(2500) NULL,
    `LAST_UPDATED` DATETIME(6) NULL,

    INDEX `JOB_INST_EXEC_FK`(`JOB_INSTANCE_ID`),
    PRIMARY KEY (`JOB_EXECUTION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION_CONTEXT` (
    `JOB_EXECUTION_ID` BIGINT NOT NULL,
    `SHORT_CONTEXT` VARCHAR(2500) NOT NULL,
    `SERIALIZED_CONTEXT` TEXT NULL,

    PRIMARY KEY (`JOB_EXECUTION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION_PARAMS` (
    `JOB_EXECUTION_ID` BIGINT NOT NULL,
    `PARAMETER_NAME` VARCHAR(100) NOT NULL,
    `PARAMETER_TYPE` VARCHAR(100) NOT NULL,
    `PARAMETER_VALUE` VARCHAR(2500) NULL,
    `IDENTIFYING` CHAR(1) NOT NULL,

    INDEX `JOB_EXEC_PARAMS_FK`(`JOB_EXECUTION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION_SEQ` (
    `ID` BIGINT NOT NULL,
    `UNIQUE_KEY` CHAR(1) NOT NULL,

    UNIQUE INDEX `UNIQUE_KEY_UN`(`UNIQUE_KEY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_JOB_INSTANCE` (
    `JOB_INSTANCE_ID` BIGINT NOT NULL,
    `VERSION` BIGINT NULL,
    `JOB_NAME` VARCHAR(100) NOT NULL,
    `JOB_KEY` VARCHAR(32) NOT NULL,

    UNIQUE INDEX `JOB_INST_UN`(`JOB_NAME`, `JOB_KEY`),
    PRIMARY KEY (`JOB_INSTANCE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_JOB_SEQ` (
    `ID` BIGINT NOT NULL,
    `UNIQUE_KEY` CHAR(1) NOT NULL,

    UNIQUE INDEX `UNIQUE_KEY_UN`(`UNIQUE_KEY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_STEP_EXECUTION` (
    `STEP_EXECUTION_ID` BIGINT NOT NULL,
    `VERSION` BIGINT NOT NULL,
    `STEP_NAME` VARCHAR(100) NOT NULL,
    `JOB_EXECUTION_ID` BIGINT NOT NULL,
    `CREATE_TIME` DATETIME(6) NOT NULL,
    `START_TIME` DATETIME(6) NULL,
    `END_TIME` DATETIME(6) NULL,
    `STATUS` VARCHAR(10) NULL,
    `COMMIT_COUNT` BIGINT NULL,
    `READ_COUNT` BIGINT NULL,
    `FILTER_COUNT` BIGINT NULL,
    `WRITE_COUNT` BIGINT NULL,
    `READ_SKIP_COUNT` BIGINT NULL,
    `WRITE_SKIP_COUNT` BIGINT NULL,
    `PROCESS_SKIP_COUNT` BIGINT NULL,
    `ROLLBACK_COUNT` BIGINT NULL,
    `EXIT_CODE` VARCHAR(2500) NULL,
    `EXIT_MESSAGE` VARCHAR(2500) NULL,
    `LAST_UPDATED` DATETIME(6) NULL,

    INDEX `JOB_EXEC_STEP_FK`(`JOB_EXECUTION_ID`),
    PRIMARY KEY (`STEP_EXECUTION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_STEP_EXECUTION_CONTEXT` (
    `STEP_EXECUTION_ID` BIGINT NOT NULL,
    `SHORT_CONTEXT` VARCHAR(2500) NOT NULL,
    `SERIALIZED_CONTEXT` TEXT NULL,

    PRIMARY KEY (`STEP_EXECUTION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `BATCH_STEP_EXECUTION_SEQ` (
    `ID` BIGINT NOT NULL,
    `UNIQUE_KEY` CHAR(1) NOT NULL,

    UNIQUE INDEX `UNIQUE_KEY_UN`(`UNIQUE_KEY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `DailyTemperature` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `afternoonTemperature` DOUBLE NULL,
    `date` DATE NULL,
    `eveningTemperature` DOUBLE NULL,
    `morningTemperature` DOUBLE NULL,
    `nightTemperature` DOUBLE NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `DayTemperature` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `afternoonTemperature` DOUBLE NULL,
    `date` DATE NULL,
    `eveningTemperature` DOUBLE NULL,
    `morningTemperature` DOUBLE NULL,
    `nightTemperature` DOUBLE NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BATCH_JOB_EXECUTION` ADD CONSTRAINT `JOB_INST_EXEC_FK` FOREIGN KEY (`JOB_INSTANCE_ID`) REFERENCES `BATCH_JOB_INSTANCE`(`JOB_INSTANCE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `BATCH_JOB_EXECUTION_CONTEXT` ADD CONSTRAINT `JOB_EXEC_CTX_FK` FOREIGN KEY (`JOB_EXECUTION_ID`) REFERENCES `BATCH_JOB_EXECUTION`(`JOB_EXECUTION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `BATCH_JOB_EXECUTION_PARAMS` ADD CONSTRAINT `JOB_EXEC_PARAMS_FK` FOREIGN KEY (`JOB_EXECUTION_ID`) REFERENCES `BATCH_JOB_EXECUTION`(`JOB_EXECUTION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `BATCH_STEP_EXECUTION` ADD CONSTRAINT `JOB_EXEC_STEP_FK` FOREIGN KEY (`JOB_EXECUTION_ID`) REFERENCES `BATCH_JOB_EXECUTION`(`JOB_EXECUTION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `BATCH_STEP_EXECUTION_CONTEXT` ADD CONSTRAINT `STEP_EXEC_CTX_FK` FOREIGN KEY (`STEP_EXECUTION_ID`) REFERENCES `BATCH_STEP_EXECUTION`(`STEP_EXECUTION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

